# Generated by Django 4.1.3 on 2022-12-15 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 15, 22, 16, 54, 887856)),
        ),
    ]
